spring:
  application:
    name: service-product-duo
server:
  port: 10004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
