spring:
  application:
    name: turbine
  main:
    allow-bean-definition-overriding: true #turbine
server:
  port: 10006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
turbine:
  app-config: service-product , service-comsume
  aggregator:
    cluster-config: default
  instanceUrlSuffix:
    default: hystrix.stream
  cluster-name-expression: new String("default")
