spring:
  application:
    name: zuul
server:
  port: 10007

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
zuul:
  routes:
      api-web:
        path: /api/web/**
        url:  http://localhost:10004/
      api-app:
        path: /api/app/**
        url:  http://localhost:10005/
