spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evofdy/config.git
          search-paths:
          default-label: master
          username:
          password:
server:
  port: 10008

#test http://localhost:10008/springcloud-dev.yml
#     http://localhost:10008/springcloud/dev/master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
