spring:
  application:
    name: zuul
server:
  port: 10007

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}

zuul:
  routes:
    service-comsume:
      path: /service-comsume/**
      serviceId: service-comsume
#  ignored-services: service-product

#ribbon
service-product:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 110000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1
    PoolMaxThreads: 100
    MaxConnectionsPerHost: 100
    MaxTotalConnections: 200


#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #>ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
