spring:
  application:
    name: zuul
server:
  port: 10007

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}

zuul:
  routes:
    service-comsume:
      path: /service-comsume/**
      serviceId: service-comsume
  #http-timeout>ribbon-timeout
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
